

spring:
  application:
     name: CrossMall
  datasource:
     url: jdbc:mysql://localhost:3306/cross-mall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  data:
    redis:
      host: localhost
      port: 6379
      # password: xxx    # 有密码才写
  session:
    store-type: redis
    timeout: 30m
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: edu.cafuc.crossmall.pojo


